[project]
name = "patent-analyser-fyp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bli>=0.1.2b0",
    "bs4>=0.0.2",
    "firestore>=0.0.8",
    "pdf2image>=1.17.0",
    "pytesseract>=0.3.13",
    "selenium>=4.29.0",
]
