[project]
name = "patent-analyser-fyp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "datasets>=3.5.0",
    "dotenv>=0.9.9",
    "friendli>=0.7.4",
    "langchain>=0.3.23",
    "langchain-openai>=0.3.14",
    "langgraph>=0.4.1",
    "langgraph-checkpoint>=2.0.25",
    "openai>=1.75.0",
    "pandas>=2.2.3",
    "polars>=1.27.1",
    "pydantic>=2.11.3",
    "python-dotenv>=1.1.0",
    "qdrant-client>=1.13.3",
    "scikit-learn>=1.6.1",
    "selenium>=4.31.0",
    "sentence-transformers>=4.1.0",
    "together>=1.5.5",
    "torchvision>=0.21.0",
    "transformers>=4.51.3",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "uv>=0.6.16",
]
