triz_keywords_mapping = {
    "Segmentation": ["divide", "split", "separate", "modular", "segment", "break down"],
    "Taking Out": ["extract", "remove", "detach", "eliminate", "exclude", "isolate"],
    "Local Quality": ["customize", "specific", "adapt", "tailored", "region-specific"],
    "Asymmetry": ["symmetrical", "asymmetrical", "uneven", ],
    "Merging": ["merge", "together", "assemble"],
    "Universality": ["multiple functions", ""],
    "Nested Doll": ["", ""],
    "Anti-weight": ["", ""],
    "Preliminary Anti-action": ["", ""],
    "Preliminary Action": ["", ""],
    "Beforehand Cushioning": ["", ""],
    "Equipotentiality": ["", ""],
    "Inversion": ["", ""],
    "Spheroidality": ["", ""],
    "Dynamics": ["", ""],
    "Partial or Excessive Actions": ["", ""],
    "Another Dimension": ["", ""],
    "Mechanical Vibration": ["", ""],
    "Periodic Action": ["", ""],
    "Continuity of Useful Action": ["", ""],
    "Skipping": ["", ""],
    "Blessing in Disguise": ["", ""],
    "Feedback": ["review", "complaint"],
    "Intermediary": ["", ""],
    "Self-service": ["", ""],
    "Copying": ["replace", ""],
    "Cheap Short-living Objects": ["", ""],
    "Mechanics Substitution": ["", ""],
    "Pneumatics and Hydraulics": ["", ""],
    "Flexible Shells and Thin Films": ["", ""],
    "Porous Materials": ["", ""],
    "Color Changes": ["", ""],
    "Homogeneity": ["", ""],
    "Discarding and Recovering": ["", ""],
    "Parameter Changes": ["", ""],
    "Phase Transitions": ["", ""],
    "Thermal Expansion": ["", ""],
    "Strong Oxidants": ["", ""],
    "Inert Atmosphere": ["", ""],
    "Composite Materials": ["", ""]
}